apiVersion: v1
kind: Service
metadata:
  name: fusionpact-service
spec:
  selector:
    app: fusionpact-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: fusionpact-backend-service
spec:
  selector:
    app: fusionpact-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

