apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fusionpact-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fusionpact.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fusionpact-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fusionpact-backend-service
                port:
                  number: 5000

